### ISSUE TITLE
unit test

### ISSUE THREAD

**Issue by 0xweb3builder** [norestlabs/libcrypto-js#2]
proceed unit test.

- crypto.generateKeys
- crypto.keysFromPassword
- crypto.PrivateKey
- crypto.PublicKey
- crypto.sha256
- crypto.ripemd160

**Comment by tonyz-defi** [comment]
![image](https://user-images.githubusercontent.com/42106554/49820127-cc6d5480-fdc2-11e8-9297-986bc41f17c1.png)

**Comment by tonyz-defi** [comment]
all unit test cases passed.

**Comment by tonyz-defi** [comment]
- test code
```
const crypto = require('@knowledgr/libcrypto');
const keys = crypto.generateKeys();
console.log('>>>>>>>> keys >>>>>>>>>');
console.log(keys);
```

- result
![image](https://user-images.githubusercontent.com/42106554/49820769-81544100-fdc4-11e8-8e7d-f603d80e4503.png)

**Comment by 0xweb3builder** [comment]
good for test.
